# Generated by Django 3.2.4 on 2021-06-30 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('altaria', '0002_post_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
