# Generated by Django 3.2.4 on 2021-06-30 04:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('altaria', '0003_alter_post_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='caption',
            field=models.TextField(default="", max_length=200),
            preserve_default=False,
        ),
    ]
