# Generated by Django 3.2.4 on 2021-06-30 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('altaria', '0005_alter_post_caption'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
